export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const SEARCH_ITEMS = "SEARCH_ITEMS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOADED = "USER_LOADED";

export const USER_COCKTAILS = "USER_COCKTAILS"
export const FETCH_COCKTAIL = "FETCH_COCKTAIL";

export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const UPDATE_USER = "UPDATE_USER";
export const FETCH_USER_LISTS = "FETCH_USER_LISTS";
export const UPDATE_INGREDIENTS = "UPDATE_INGREDIENTS";

export const ADD_MUST_HAVE = "ADD_MUST_HAVE";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";


export const REMOVE_MUST_HAVE = "REMOVE_MUST_HAVE";











